import { connect } from 'react-redux'
import { State } from '../reducers'
import { getTodos } from '../selectors/todos'
import { updateTodo, deleteTodo } from '../actions/todos'
import TodoList from '../components/TodosList'